variable "location" {}
variable "type" {}
variable "source_port_range" {}
variable "destination_address_prefix" {}
variable "source_address_prefix" {}
variable "destination_port_range" {}
variable "protocol" {}
variable "address_prefix" {}
variable "address_space" {}
